#!/usr/bin/env python3
"""Generate data/rules/airlog/DECISIONS.md: every airlog decision case, grouped by seat and timing.

Usage: python tools/rules/airlog_decisions.py          (rewrites DECISIONS.md)
       python tools/rules/airlog_decisions.py --check  (exit 1 if DECISIONS.md is out of date)
Requires Python >= 3.11 (tomllib).
"""
from __future__ import annotations

import sys
import tomllib
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RULES = REPO / "data" / "rules" / "airlog"
OUT = RULES / "DECISIONS.md"

SEAT_ORDER = ["commander", "front_line", "rear_area", "logistics", "air", "naval", "either"]


def collect():
    rows = []
    for p in sorted(RULES.glob("[0-9][0-9]-*.toml")):
        data = tomllib.loads(p.read_text(encoding="utf-8"))
        for c in data.get("case", []):
            if c.get("disposition") != "decision":
                continue
            rows.append((c, p.name))
    return rows


def render(rows) -> str:
    by_seat: dict[str, list] = defaultdict(list)
    for c, f in rows:
        by_seat[c["seat"]].append((c, f))
    lines = [
        "# Air & Logistics decision cases",
        "",
        "Generated by `tools/rules/airlog_decisions.py` from the registry; do not edit by hand.",
        f"{len(rows)} decision cases. Grouped by seat, then by primary timing anchor (the first listed).",
        "",
    ]
    seats = [s for s in SEAT_ORDER if s in by_seat] + sorted(s for s in by_seat if s not in SEAT_ORDER)
    for seat in seats:
        items = by_seat[seat]
        lines.append(f"## Seat: {seat} ({len(items)})")
        lines.append("")
        by_timing: dict[str, list] = defaultdict(list)
        for c, f in items:
            by_timing[(c.get("timing") or ["(none)"])[0]].append(c)
        for timing in sorted(by_timing):
            lines.append(f"### `{timing}`")
            lines.append("")
            for c in sorted(by_timing[timing], key=lambda x: [int(t) if t.isdigit() else 0 for t in x["id"].replace("-", ".").split(".")[:2]] + [x["id"]]):
                d = c["decision"]
                more = [t for t in c["timing"][1:]]
                extra = f" (also: {', '.join('`'+t+'`' for t in more)})" if more else ""
                lines.append(
                    f"- **{c['id']}** — {d['what']}{extra} "
                    f"[trigger: {d['trigger']}; secrecy: {d['secrecy']}"
                    f"{'; interrupts' if d.get('interrupts') else ''}; "
                    f"params: {', '.join(d['params'])}; graziani: {c['applies']['graziani']}]"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    text = render(collect())
    if "--check" in sys.argv:
        return 0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
