#!/usr/bin/env python3
"""Generate the decision catalogue (data/rules/<book>/DECISIONS.md) from the rule-case registry.

Lists every case with disposition = "decision", grouped by owning seat and then by sequence-of-play
timing (in the order of the timing vocabulary of data/rules/README.md). Python >= 3.11.

Usage:
    python tools/rules/decisions_catalogue.py --book land          # write data/rules/land/DECISIONS.md
    python tools/rules/decisions_catalogue.py --book land --check  # exit 1 if the file is out of date
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SEAT_ORDER = ["commander", "front_line", "rear_area", "logistics", "air", "naval", "either", "none"]

TIMING_ORDER = [
    "setup", "initiative", "strategic_air", "naval_convoy", "logistics",
    "opstage.initiative_declaration", "opstage.weather", "opstage.organization",
    "opstage.convoy_arrival", "opstage.cw_fleet", "opstage.land_support_air",
    "opstage.reserve_designation", "opstage.movement_and_combat.movement",
    "opstage.movement_and_combat.breakdown", "opstage.movement_and_combat.combat",
    "opstage.movement_and_combat.reserve_release", "opstage.movement_and_combat",
    "opstage.truck_convoy_movement", "opstage.cw_rail_movement", "opstage.repair",
    "opstage.patrol", "strategic_air_recovery", "end_of_turn", "continuous", "end_of_game",
]


def timing_rank(t: str) -> tuple[int, str]:
    for i, prefix in enumerate(TIMING_ORDER):
        if t == prefix or t.startswith(prefix + "."):
            return (i, t)
    return (len(TIMING_ORDER), t)


def load_decisions(book: str):
    out = []
    for p in sorted((REPO / "data" / "rules" / book).glob("[0-9][0-9]-*.toml")):
        doc = tomllib.loads(p.read_text(encoding="utf-8"))
        for c in doc.get("case", []):
            if c.get("disposition") == "decision":
                out.append(c)
    return out


def render(book: str) -> str:
    cases = load_decisions(book)
    by_seat: dict[str, list[dict]] = {}
    for c in cases:
        by_seat.setdefault(c["seat"], []).append(c)
    lines = [
        f"# Decision catalogue: {book} rulebook",
        "",
        "Generated by `tools/rules/decisions_catalogue.py` from the rule-case registry; do not edit by hand.",
        f"{len(cases)} decision cases. Grouped by owning seat, then by first timing anchor in the sequence of play.",
        "Columns: case, short title, the decision, params, trigger (scheduled at a phase, triggered by an event,",
        "or standing policy), secrecy, whether it interrupts another action, and whether it can arise in",
        "Graziani's Offensive (yes / no / conditional).",
        "",
    ]
    for seat in SEAT_ORDER:
        group = by_seat.get(seat)
        if not group:
            continue
        group.sort(key=lambda c: (timing_rank(c["timing"][0])[0] if c["timing"] else 99,
                                  [int(x) if x.isdigit() else 0 for x in c["id"].replace("a", ".").split(".")]))
        lines += [f"## Seat: {seat} ({len(group)})", "",
                  "| Case | Title | Decision | Params | Trigger | Secrecy | Int. | Timing | Graz. |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for c in group:
            d = c["decision"]
            lines.append("| " + " | ".join([
                f"land:{c['id']}", c["title"].replace("|", "/"), d["what"].replace("|", "/"),
                "; ".join(d["params"]).replace("|", "/"), d["trigger"], d["secrecy"],
                "yes" if d["interrupts"] else "no",
                ", ".join(c["timing"]), c["applies"]["graziani"]]) + " |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", default="land")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render(args.book)
    dest = REPO / "data" / "rules" / args.book / "DECISIONS.md"
    if args.check:
        if not dest.exists() or dest.read_text(encoding="utf-8") != text:
            print(f"{dest} is out of date", file=sys.stderr)
            return 1
        return 0
    dest.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {dest} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
