[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/Maurdekye/neo-sandtable"
authors = ["maurdekye"]
version = "0.1.0"

[workspace.dependencies]
rand_core = "0.9"
rand_chacha = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ts-rs = { version = "12", features = ["serde-json-impl"] }
csv = "1"
toml = "0.9"
serde_path_to_error = "0.1"
cna-core = { path = "crates/cna-core" }
cna-protocol = { path = "crates/cna-protocol" }
cna-content = { path = "crates/cna-content" }
cna-tables = { path = "crates/cna-tables" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
float_arithmetic = "warn"
